VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IGroupAssignable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

'namespace=/vba-files/track-race/modules/program-entry/policy
Option Explicit

Public Function AssignGroup(ByRef Qualifiers As QualifiedAthleteModels, ByVal PersonsPerGroup As Long) As QualifiedAthleteModels()
End Function
