VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IOrderAssignable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'namespace=vba-files/track-race/modules/program-entry/policy
Option Explicit

Public Function AssignOrder(ByRef Qualifiers As QualifiedAthleteModels) As QualifiedAthleteModels
End Function

Public Property Get PersonsPerGroup() As Long
End Property

