VERSION 1.0 CLASS
BEGIN
MultiUse = -1  'True
END
Attribute VB_Name = "IJsonParser"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'namespace=vba-files/common/json
Option Explicit

Public Function Parse(JsonString As String, ByVal NewObject As Object) As Object
End Function

'(Template Start) =============================================================
' Implements IJsonParser

' Private Function IJsonParser_Parse(JsonString As String, ByVal NewObject As Object) As Object
' End Function

'(Template End) ===============================================================
