VERSION 1.0 CLASS
BEGIN
MultiUse = -1  'True
END
Attribute VB_Name = "IJsonParsable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'namespace=vba-files/common/json
Option Explicit

Public Sub FromJson(JsonString As String)
End Sub

'(Template Start) =============================================================
' Implements IJsonParsable

' Public Sub FromJson(JsonString As String)
'     Call IJsonParsable_FromJson(JsonString)
' End Sub

' Private Sub IJsonParsable_FromJson(JsonString As String)
' End Sub

'(Template End) ===============================================================
