VERSION 1.0 CLASS
BEGIN
MultiUse = -1  'True
END
Attribute VB_Name = "IJsonConvertable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'namespace=vba-files/common/json
Option Explicit

Public Function ToJson() As String
End Function

'(Template Start) =============================================================
' Implements IJsonConvertable

' Public Function ToJson() As String
'     ToJson = IJsonConvertable_ToJson()
' End Function

' Private Function IJsonConvertable_ToJson() As String
' End Function

'(Template End) ===============================================================
