VERSION 1.0 CLASS
BEGIN
MultiUse = -1  'True
END
Attribute VB_Name = "IObjectClassifier"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'namespace=vba-files/common/collection
Option Explicit

Public Function Classify(Element As Object) As Variant
End Function

' (Templates Start) ===========================================================
' Implements IObjectClassifier

' Private Function IObjectClassifier_Classify(Element As Object) As Variant
' End Function

' (Templates End) =============================================================
